In [4]:
import pandas as pd
import numpy as np

In [5]:
file_path = '/content/spam.csv'

In [6]:
df = pd.read_csv('/content/spam.csv', encoding='latin-1')

In [39]:
df.head(10)

type                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [8]:
df = df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis = 1)

In [40]:
df.head(10)

type                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [10]:
import re
import nltk

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [13]:
ps = PorterStemmer()

In [14]:
corpus = []

In [15]:
for i in range(0, len(df)):
  review = re.sub('[^a-zA-z]', ' ', df['message'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [41]:
corpus[:10]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free']

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer(max_features=5000)

In [19]:
x = cv.fit_transform(corpus).toarray()

In [43]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
y = df.iloc[:,0].values

In [44]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [23]:
from sklearn import preprocessing

In [24]:
label_encoder = preprocessing.LabelEncoder()

In [25]:
y = label_encoder.fit_transform(y)

In [26]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state=0)

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
naive_model = MultinomialNB()

In [31]:
spam_detect_model = naive_model.fit(x_train, y_train)

In [32]:
y_pred = spam_detect_model.predict(x_test)

In [33]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_m = confusion_matrix(y_pred, y_test)

In [36]:
confusion_m

array([[939,   6],
       [ 10, 160]])

In [37]:
accuracy = naive_model.score(x_test, y_test)

In [38]:
accuracy

0.9856502242152466